### ISSUE TITLE
CustomFieldModelSerializer not found

### ISSUE THREAD

**Issue by bintangf** [nautobot/nautobot-plugin-device-lifecycle-mgmt#146] opened 2023-03-24 02:08 UTC
### Environment
* Python version:  3.9.13
* Nautobot version:  1.5.9
* nautobot-plugin-device-lifecycle-mgmt version:  1.1.0

### Expected Behavior
When i restart nautobot can running well and when i run _nautobot-server check_ not get any error

### Observed Behavior
```
Traceback (most recent call last):
  File "/opt/nautobot/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot/core/cli.py", line 54, in main
    run_app(
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot/core/runner/runner.py", line 263, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/nautobot/lib64/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/opt/nautobot/lib64/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot/circuits/apps.py", line 9, in ready
    super().ready()
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot/core/apps/__init__.py", line 50, in ready
    register_menu_items(menu_items)
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot/core/apps/__init__.py", line 84, in register_menu_items
    item.link = reverse(item.link, args=item.args, kwargs=item.kwargs)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/urls/base.py", line 54, in reverse
    app_list = resolver.app_dict[ns]
  File "/opt/nautobot/lib64/python3.9/site-packages/django/urls/resolvers.py", line 530, in app_dict
    self._populate()
  File "/opt/nautobot/lib64/python3.9/site-packages/django/urls/resolvers.py", line 464, in _populate
    for url_pattern in reversed(self.url_patterns):
  File "/opt/nautobot/lib64/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/nautobot/lib64/python3.9/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot/core/urls.py", line 7, in <module>
    from nautobot.extras.plugins.urls import (
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot/extras/plugins/urls.py", line 37, in <module>
    urlpatterns = import_object(f"{plugin_path}.api.urls.urlpatterns")
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot/extras/plugins/utils.py", line 45, in import_object
    spec.loader.exec_module(module)
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot_device_lifecycle_mgmt/api/urls.py", line 4, in <module>
    from nautobot_device_lifecycle_mgmt.api.views import (
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot_device_lifecycle_mgmt/api/views.py", line 29, in <module>
    from .serializers import (
  File "/opt/nautobot/lib64/python3.9/site-packages/nautobot_device_lifecycle_mgmt/api/serializers.py", line 9, in <module>
    from nautobot.extras.api.serializers import (
ImportError: cannot import name 'CustomFieldModelSerializer' from 'nautobot.extras.api.serializers' (/opt/nautobot/lib64/python3.9/site-packages/nautobot/extras/api/serializers.py
```

When I try to change CustomFieldModelSerializer to CustomFieldModelSerializerMixin inside /opt/nautobot/lib64/python3.9/site-packages/nautobot_device_lifecycle_mgmt/api/serializers.py, Nautobot can running well. 

### Steps to Reproduce
1. Install Nautobot 1.5.9
2. Install nautobot-plugin-device-lifecycle-mgmt 1.1.0
3. Try to run.

**Comment by glennmatthews** [comment] 2023-03-24 12:40
Duplicate of #122, fixed in v1.1.2 of this plugin.

**Closed by glennmatthews** 2023-03-24 12:40 UTC
